// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9IQ6chUKfkOI1ECNiFIHdgJNBrNJecJA',
    appId: '1:251023512382:web:a441ec6bdcfbaf493d126f',
    messagingSenderId: '251023512382',
    projectId: 'expenses-acbaa',
    authDomain: 'expenses-acbaa.firebaseapp.com',
    databaseURL: 'https://expenses-acbaa-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-acbaa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNk7C2zrszkmjKgfMIsq-ytYsEe41I5fI',
    appId: '1:251023512382:android:855c89c1b1ba7c273d126f',
    messagingSenderId: '251023512382',
    projectId: 'expenses-acbaa',
    databaseURL: 'https://expenses-acbaa-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-acbaa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ5G5BD1IA-2-ua3iKNnoyY4he7eS0l_4',
    appId: '1:251023512382:ios:c593390ab9432f353d126f',
    messagingSenderId: '251023512382',
    projectId: 'expenses-acbaa',
    databaseURL: 'https://expenses-acbaa-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-acbaa.appspot.com',
    iosBundleId: 'com.example.pecaExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ5G5BD1IA-2-ua3iKNnoyY4he7eS0l_4',
    appId: '1:251023512382:ios:c593390ab9432f353d126f',
    messagingSenderId: '251023512382',
    projectId: 'expenses-acbaa',
    databaseURL: 'https://expenses-acbaa-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-acbaa.appspot.com',
    iosBundleId: 'com.example.pecaExpenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9IQ6chUKfkOI1ECNiFIHdgJNBrNJecJA',
    appId: '1:251023512382:web:181a937dec008e6f3d126f',
    messagingSenderId: '251023512382',
    projectId: 'expenses-acbaa',
    authDomain: 'expenses-acbaa.firebaseapp.com',
    databaseURL: 'https://expenses-acbaa-default-rtdb.firebaseio.com',
    storageBucket: 'expenses-acbaa.appspot.com',
  );
}
